site_name: PrompGuard Technical Spec
nav:
  - Home: index.md
  - Lab Environment:
    - Introduction: lab-env/intro.md
    - High Level Design: lab-env/hlds.md
    - Transaction Risk Score: lab-env/txn-risk-score/index.md
    - Data Preparation: lab-env/data-prep.md
    - Model Evaluation Pipeline: lab-env/model-eval/index.md
    - Model Training Pipeline: lab-env/model-train/index.md
    - Fraud Engine Version Control: lab-env/version-ctrl.md
    - Common Components:
      - Redis: lab-env/common-components/redis.md
      - Kafka: lab-env/common-components/kafka.md
      - SeaweedFS: lab-env/common-components/seaweed.md
      - Postgres: lab-env/common-components/postgres.md
      - Apache Airflow: lab-env/common-components/airflow.md
  - Prod Environment: prod-env/index.md
  - API Standard: api-std.md

theme:
  name: mkdocs
  user_color_mode_toggle: true

plugins:
  - search
  - mermaid2:
      version: 11.12.2

site_url: http://localhost:3001/docs/2118723a-9383-49c2-b328-e3f273d26064/
